version: '3.3'

services:

  db:
    build: db
    image: florentnakaz/db:1.0.0

  words:
    build: words
    image: sebkhedim/words:1.0.0
    deploy:
      replicas: 5

  web:
    build: web
    image: sebkhedim/web:1.0.0
    ports:
     - "8080:80"

     #test commit actions docker-compose 2